.github/workflows/gh-pages.yml
.github/workflows/test.yml
README.md
docs/conf.py
docs/index.md
docs/index.rst
nercst/__init__.py
pyproject.toml
tests/docs/test_build.py
tests/test_nothing.py

#2 Fix bugs from template

---

.gitignore
nercst/__init__.py
nercst/core/__init__.py
nercst/core/io.py
nercst/core/struct.py
poetry.lock
pyproject.toml

**Checks**
This PR closes #...

#16 dataloader

---

.gitignore
nercst/__init__.py
nercst/core/__init__.py
nercst/core/struct.py
poetry.lock
pyproject.toml

#13 datastructure

---

nercst/core/__init__.py
nercst/core/chopper_wheel.py
nercst/core/io.py

#18 chopper-wheel module added

---

nercst/core/io.py

**Checks**
This PR closes #...

"#18 topic_getter added"

---

nercst/core/io.py

"#23 typing"

---

nercst/rsky/__init__.py
nercst/rsky/rsky.py
nercst/rsky/rsky_plot.py
poetry.lock
pyproject.toml

**Checks**
This PR closes #25 .

#25 add scripts for plot

---

nercst/core/io.py

"#29 support data loading of the new 1.85 data"

---

nercst/core/io.py

"#32 obsmodebug fixed"

---

nercst/core/io.py

#35 backward

---

nercst/skydip/__init__.py
nercst/skydip/skydip.py
nercst/skydip/slydip_plot.py

**Checks**
This PR closes #37.

#37 add skydip

---

nercst/rsky/rsky.py
nercst/rsky/rsky_plot.py

**Checks**
This PR closes #39.

#39 update about data loading

---

nercst/core/chopper_wheel.py
nercst/core/io.py

"#41 chopperwheel"

---

nercst/core/__init__.py
nercst/core/baselinefitting.py
nercst/core/chopper_wheel.py
nercst/core/io.py

#43 basefit

---

.gitignore
nercst/core/coords_converter.py
poetry.lock

"#45 coordinate converter implemented"

---

nercst/core/__init__.py
nercst/core/io.py
nercst/pointings/__init__.py
poetry.lock

**Checks**
This PR closes #...

"#56 io revised"

---

nercst/core/io.py
pyproject.toml

#59 add configfilepath

---

.github/workflows/test.yml

**Checks**
This PR closes #...

#66 Update test.yml to support newer poetry

---

nercst/core/coords_converter.py

#66 fix coords converter

---

nercst/core/io.py
nercst/core/multidimensional_coordinates.py
nercst/core/struct.py

#79 filepath
